# Generated by Django 5.1.2 on 2024-10-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='description',
        ),
    ]
