# Generated by Django 5.1.2 on 2024-10-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_remove_train_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='coach_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
