version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:8000
      - API_TRAIN=http://localhost:8001
      - API_BOOKING=http://localhost:8002