# Generated by Django 5.1.2 on 2024-10-24 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('seat_id', models.UUIDField()),
                ('payment_id', models.UUIDField(blank=True, null=True)),
                ('otp', models.IntegerField(default=612086)),
                ('amount_payable', models.FloatField()),
                ('payment_done', models.BooleanField(default=False)),
                ('booking_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
