version: "3.8"
services:
  auth:
    container_name: dj-auth
    build:
      context: ./auth/src
    ports:
      - 8000:8000
    volumes:
      - ./auth/src:/usr/src/app

  train:
    container_name: dj-train
    build:
      context: ./train/src
    ports:
      - 8001:8000
    volumes:
      - ./train/src:/usr/src/app

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: "rabbitmq"
    ports:
      # - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 20s
      timeout: 10s
      retries: 5

  booking:
    container_name: dj-booking
    build:
      context: ./booking/src
    ports:
      - 8002:8000
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./booking/src:/usr/src/app

  notification:
    container_name: dj-notification
    build:
      context: ./notification/src
    ports:
      - 8003:8000
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./notification/src:/usr/src/app
