version: "3.8"
services:
  auth:
    container_name: dj-auth
    build:
      context: ./auth/src
    ports:
      - 8000:8000
  train:
    container_name: dj-train
    build:
      context: ./train/src
    ports:
      - 8001:8000

  booking:
    container_name: dj-booking
    build:
      context: ./booking/src
    ports:
      - 8002:8000
