name: Django CI Pipeline

on:
  push:
    branches:
      - auth
      - trains
      - booking
      - notifications
  pull_request:
    branches:
      - auth
      - trains
      - booking
      - notifications

jobs:
  test-auth:
    name: Test Auth Service
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/auth' || github.ref == 'refs/pull/auth'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/auth/src/requirements.txt

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:/src/auth/src/" >> $GITHUB_ENV

      - name: Run Migrations
        run: |
          python src/auth/src/manage.py makemigrations
          python src/auth/src/manage.py migrate
        env:
          DJANGO_SETTINGS_MODULE: src.auth.src.core.settings
          PYTHONPATH: ${{ env.PYTHONPATH }}

      - name: Run Tests
        run: |
          python src/auth/src/manage.py test accounts -v 2

        env:
          DJANGO_SETTINGS_MODULE: src.auth.src.core.settings
          PYTHONPATH: ${{ env.PYTHONPATH }}

  test-trains:
    name: Test Trains Service
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/trains' || github.ref == 'refs/pull/trains'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/train/src/requirements.txt

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:/src/train/src/" >> $GITHUB_ENV

      - name: Run Migrations
        run: |
          python src/train/src/manage.py makemigrations
          python src/train/src/manage.py migrate
        env:
          DJANGO_SETTINGS_MODULE: src.train.src.core.settings
          PYTHONPATH: ${{ env.PYTHONPATH }}

      - name: Run Tests
        run: |
          python src/train/src/manage.py test trains -v 2

        env:
          DJANGO_SETTINGS_MODULE: src.train.src.core.settings
          PYTHONPATH: ${{ env.PYTHONPATH }}

  test-booking:
    name: Test Booking Service
    runs-on: ubuntu latest

    if: github.ref == 'refs/heads/booking' || github.ref == 'refs/pull/booking'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/booking/src/requirements.txt

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:/src/booking/src/" >> $GITHUB_ENV

      - name: Run Migrations
        run: |
          python src/booking/src/manage.py makemigrations
          python src/booking/src/manage.py migrate
        env:
          DJANGO_SETTINGS_MODULE: src.booking.src.core.settings
          PYTHONPATH: ${{ env.PYTHONPATH }}

      - name: Run Tests
        run: |
          python src/booking/src/manage.py test bookings -v 2

        env:
          DJANGO_SETTINGS_MODULE: src.booking.src.core.settings
          PYTHONPATH: ${{ env.PYTHONPATH }}

  test-notifications:
    name: Test Notifications Service
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/notifications' || github.ref == 'refs/pull/notifications'
    steps:
      - uses: actions/checkout@v3

      - name: Mock Notification Service
        run: |
          echo "Mocking Notification Service"
