name: Django CI Pipeline

on:
  push:
    branches:
      - auth
      - trains
  pull_request:
    branches:
      - auth
      - trains

jobs:
  test-auth:
    name: Test Auth Service
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/auth' || github.ref == 'refs/pull/auth'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/auth/src/requirements.txt

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:/src/auth/src/" >> $GITHUB_ENV

      - name: Run Migrations
        run: |
          python src/auth/src/manage.py makemigrations
          python src/auth/src/manage.py migrate
        env:
          DJANGO_SETTINGS_MODULE: src.auth.src.core.settings
          PYTHONPATH: ${{ env.PYTHONPATH }}

      - name: Run Tests
        run: |
          python src/auth/src/manage.py test accounts -v 2

        env:
          DJANGO_SETTINGS_MODULE: src.auth.src.core.settings
          PYTHONPATH: ${{ env.PYTHONPATH }}

  test-trains:
    name: Test Trains Service
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/trains' || github.ref == 'refs/pull/trains'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/trains/src/requirements.txt

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:/src/trains/src/" >> $GITHUB_ENV

      - name: Run Migrations
        run: |
          python src/trains/src/manage.py makemigrations
          python src/trains/src/manage.py migrate
        env:
          DJANGO_SETTINGS_MODULE: src.trains.src.core.settings
          PYTHONPATH: ${{ env.PYTHONPATH }}

      - name: Run Tests
        run: |
          python src/trains/src/manage.py test trains -v 2

        env:
          DJANGO_SETTINGS_MODULE: src.trains.src.core.settings
          PYTHONPATH: ${{ env.PYTHONPATH }}
