name: Django CI/CD

on:
  push:
    branches:
      - main
      - auth
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/auth/src/requirements.txt

      - name: Create .env file
        run: |
          echo "DATABASE_ENGINE=django.db.backends.postgresql" >> .env
          echo "DATABASE_NAME=test_db" >> .env
          echo "DATABASE_USER=postgres" >> .env
          echo "DATABASE_PASSWORD=postgres" >> .env
          echo "DATABASE_HOST=localhost" >> .env
          echo "DATABASE_PORT=5432" >> .env
          echo "TEST_DATABASE_NAME=test_db" >> .env

      - name: Run Tests
        run: |
          pytest
        env:
          DJANGO_SETTINGS_MODULE: src.auth.src.core.settings
